-- vim.g.do_filetype_lua = 1
-- vim.g.did_load_filetypes = 0

-- vim.filetype.add({
--   extension = {
--     altarica = "alt",
--   },
--   filename = {
--     [".alt"] = "alt",
--   },
--   pattern = {
--     [".*/etc/foo/.*%.conf"] = "foorc",
--   },
-- })
