
require("lspsaga")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.lsp_status")
require("plugins.lualine")
require("plugins.comments")
require("plugins.luasnip")
require("plugins.treesitter")
require("plugins.gutter")
require("luasnip.loaders.from_vscode").load()
